language: python

python:
  - "2.6"
  - "2.7"

branches:
  only:
    - master
    - dev

install:  pip install -r requirements.txt --use-mirrors

script: python setup.py test

notifications:
  email: false
